AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

inherit_gem:
  prettier: rubocop.yml
