default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: wnb_rb_site_development
  username: postgres
  password: root
test:
  <<: *default
  database: wnb_rb_site_test
  username: postgres
  password: root
# TODO: edit this with production details
production:
  <<: *default
  database: YOUR_APP_NAME_HERE_production
  username: YOUR_APP_NAME_HERE
  password: <%= ENV['YOUR_APP_NAME_HERE_DATABASE_PASSWORD'] %>
